homepage: "https://example.com/buffer-overflow-demo"
language: c
primary_contact: "demo@example.com"
main_repo: "https://github.com/example/buffer-overflow-demo"
sanitizers:
  - address
  - undefined
fuzzing_engines:
  - libfuzzer
